AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "FastAPI con LLM en Lambda"

Globals:
  Function:
    Timeout: 60
    MemorySize: 250

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fastapi-llm
      CodeUri: app
      Handler: main.handler
      Runtime: python3.13
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          togetherApiKey: 152cda2952b7febf574eef62d60cecc33a896b5a61c9cce7dc9e71c7ff50acd3


Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

